<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<RootNamespace>RclStaticSites</RootNamespace>
		<AssemblyName>RclStaticSites</AssemblyName>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>0.0.5</Version>
		<Company>CodeB</Company>
		<Authors>CodeB</Authors>
		<Description>Razor Class library</Description>
		<PackageReadmeFile>readme.md</PackageReadmeFile>

	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.6" />
	</ItemGroup>

	<ItemGroup>
		<None Include="docs\readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>


	<ItemGroup>
		<Content Update="wwwroot\css\app.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>



	<!-- Only pack on rlease. This allows for debugging -->
	<Target Condition="'$(Configuration)' == 'Release'" Name="CopyPackage" AfterTargets="Pack">
		<!--<Copy SourceFiles="$(ProjectDir)\bin\Release\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="C:\Users\mcasas\Desktop\PublishedApps\Rcl" />-->
    <Copy SourceFiles="$(ProjectDir)\bin\Release\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="C:\Users\mc\Desktop\PublishedApps\Rcl" />
	</Target>

</Project>
